import { ImageSourcePropType } from "react-native";

export const isl_gif = [
  {
    name: "address",
    value: require("./assets/images/address.gif"),
  },
  {
    name: "are you angry",
    value: require("./assets/images/are-you-angry.gif"),
  },
  {
    name: "are you busy",
    value: require("./assets/images/are-you-busy.gif"),
  },
  {
    name: "are you hungry",
    value: require("./assets/images/are-you-hungry.gif"),
  },
  {},
  // 'are you sick',
  // 'be careful',
  // 'can we meet tomorrow',
  // 'did you book tickets',
  // 'did you finish homework',
  // 'do you go to office',
  // 'do you have money',
  // 'do you want something to drink',
  // 'do you want tea or coffee',
  // 'do you watch TV',
  // 'dont worry',
  // 'flower is beautiful',
  // 'good afternoon',
  // 'good evening',
  // 'good morning',
  // 'good night',
  // 'good question',
  // 'had your lunch',
  // 'happy journey',
  // 'hello what is your name',
  // 'how many people are there in your family',
  // 'i am a clerk',
  // 'i am bore doing nothing',
  // 'i am fine',
  // 'i am sorry',
  // 'i am thinking',
  // 'i am tired',
  // 'i dont understand anything',
  // 'i go to a theatre',
  // 'i love to shop',
  // 'i had to say something but I forgot',
  // 'i have headache',
  // 'i like pink colour',
  // 'i live in nagpur',
  // 'lets go for lunch',
  // 'my mother is a homemaker',
  // 'my name is john',
  // 'nice to meet you',
  // 'no smoking please',
  // 'open the door',
  // 'please call me later',
  // 'please clean the room',
  // 'please give me your pen',
  // 'please use dustbin dont throw garbage',
  // 'please wait for sometime',
  // 'shall I help you',
  // 'shall we go together tommorow',
  // 'sign language interpreter',
  // 'sit down',
  // 'stand up',
  // 'take care',
  // 'there was traffic jam',
  // 'wait I am thinking',
  // 'what are you doing',
  // 'what is the problem',
  // 'what is todays date',
  // 'what is your father do',
  // 'what is your job',
  // 'what is your mobile number',
  // 'what is your name',
  // 'whats up',
  // 'when is your interview',
  // 'when we will go',
  // 'where do you stay',
  // 'where is the bathroom',
  // 'where is the police station',
  // 'you are wrong',
  // 'address',
  // 'agra',
  // 'ahmedabad',
  // 'all',
  // 'april',
  // 'assam',
  // 'august',
  // 'australia',
  // 'badoda',
  // 'banana',
  // 'banaras',
  // 'banglore',
  // 'bihar',
  // 'bihar',
  // 'bridge',
  // 'cat',
  // 'chandigarh',
  // 'chennai',
  // 'christmas',
  // 'church',
  // 'clinic',
  // 'coconut',
  // 'crocodile',
  // 'dasara',
  // 'deaf',
  // 'december',
  // 'deer',
  // 'delhi',
  // 'dollar',
  // 'duck',
  // 'february',
  // 'friday',
  // 'fruits',
  // 'glass',
  // 'grapes',
  // 'gujarat',
  // 'hello',
  // 'hindu',
  // 'hyderabad',
  // 'india',
  // 'january',
  // 'jesus',
  // 'job',
  // 'july',
  // 'july',
  // 'karnataka',
  // 'kerala',
  // 'krishna',
  // 'litre',
  // 'mango',
  // 'may',
  // 'mile',
  // 'monday',
  // 'mumbai',
  // 'museum',
  // 'muslim',
  // 'nagpur',
  // 'october',
  // 'orange',
  // 'pakistan',
  // 'pass',
  // 'police station',
  // 'post office',
  // 'pune',
  // 'punjab',
  // 'rajasthan',
  // 'ram',
  // 'restaurant',
  // 'saturday',
  // 'september',
  // 'shop',
  // 'sleep',
  // 'southafrica',
  // 'story',
  // 'sunday',
  // 'tamil nadu',
  // 'temperature',
  // 'temple',
  // 'thursday',
  // 'toilet',
  // 'tomato',
  // 'town',
  // 'tuesday',
  // 'usa',
  // 'village',
  // 'voice',
  // 'wednesday',
  // 'weight',
  // 'please wait for sometime',
  // 'what is your mobile number',
  // 'what are you doing',
  // 'are you busy',
];

export const arr = [
  { name: "a", value: require("./assets/letters/a.jpg") },
  { name: "b", value: require("./assets/letters/b.jpg") },
  { name: "c", value: require("./assets/letters/c.jpg") },
  { name: "d", value: require("./assets/letters/d.jpg") },
  { name: "e", value: require("./assets/letters/e.jpg") },
  { name: "f", value: require("./assets/letters/f.jpg") },
  { name: "g", value: require("./assets/letters/g.jpg") },
  { name: "h", value: require("./assets/letters/h.jpg") },
  { name: "i", value: require("./assets/letters/i.jpg") },
  { name: "j", value: require("./assets/letters/j.jpg") },
  { name: "k", value: require("./assets/letters/k.jpg") },
  { name: "l", value: require("./assets/letters/l.jpg") },
  { name: "m", value: require("./assets/letters/m.jpg") },
  { name: "n", value: require("./assets/letters/n.jpg") },
  { name: "o", value: require("./assets/letters/o.jpg") },
  { name: "p", value: require("./assets/letters/p.jpg") },
  { name: "q", value: require("./assets/letters/q.jpg") },
  { name: "r", value: require("./assets/letters/r.jpg") },
  { name: "s", value: require("./assets/letters/s.jpg") },
  { name: "t", value: require("./assets/letters/t.jpg") },
  { name: "u", value: require("./assets/letters/u.jpg") },
  { name: "v", value: require("./assets/letters/v.jpg") },
  { name: "w", value: require("./assets/letters/w.jpg") },
  { name: "x", value: require("./assets/letters/x.jpg") },
  { name: "y", value: require("./assets/letters/y.jpg") },
  { name: "z", value: require("./assets/letters/z.jpg") },
  // 'a',
  // 'b',
  // 'c',
  // 'd',
  // 'e',
  // 'f',
  // 'g',
  // 'h',
  // 'i',
  // 'j',
  // 'k',
  // 'l',
  // 'm',
  // 'n',
  // 'o',
  // 'p',
  // 'q',
  // 'r',
  // 's',
  // 't',
  // 'u',
  // 'v',
  // 'w',
  // 'x',
  // 'y',
  // 'z',
];
