import { ImageSourcePropType } from "react-native";

export const isl_gif = [
  // {
  //   name: "any questions",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/any questions.gif"),
  // },
  // {
  //   name: "are you angry",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/are you angry.gif"),
  // },
  // {
  //   name: "are you busy",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/are you busy.gif"),
  // },
  // {
  //   name: "are you hungry",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/are you hungry.gif"),
  // },
  // {
  //   name: "are you sick",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/are you sick.gif"),
  // },
  // {
  //   name: "be careful",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/be careful.gif"),
  // },
  // {
  //   name: "can we meet tomorrow",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/can we meet tomorrow.gif"),
  // },
  // {
  //   name: "did you book tickets",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/did you book tickets.gif"),
  // },
  // {
  //   name: 'did you finish homework',
  //   value: require('/assets/images/did you finish homework.gif'),
  // },
  // {
  //   name: 'do you go to office',
  //   value: require('/assets/images/do you go to office.gif'),
  // },
  // {
  //   name: 'do you have money',
  //   value: require('/assets/images/do you have money.gif'),
  // },
  // {
  //   name: 'do you want something to drink',
  //   value: require('/assets/images/do you want something to drink.gif'),
  // },
  // {
  //   name: 'do you want tea or coffee',
  //   value: require('/assets/images/do you want tea or coffee.gif'),
  // },
  // {
  //   name: 'do you watch TV',
  //   value: require('/assets/images/do you watch TV.gif'),
  // },
  // {name: 'dont worry', value: require('/assets/images/dont worry.gif')},
  // {
  //   name: 'flower is beautiful',
  //   value: require('/assets/images/flower is beautiful.gif'),
  // },
  // {name: 'good afternoon', value: require('/assets/images/good afternoon.gif')},
  // {name: 'good evening', value: require('/assets/images/good evening.gif')},
  // {name: 'good morning', value: require('/assets/images/good morning.gif')},
  // {name: 'good night', value: require('/assets/images/good night.gif')},
  // {name: 'good question', value: require('/assets/images/good question.gif')},
  // {name: 'had your lunch', value: require('/assets/images/had your lunch.gif')},
  // {name: 'happy journey', value: require('/assets/images/happy journey.gif')},
  // {
  //   name: 'hello what is your name',
  //   value: require('/assets/images/hello what is your name.gif'),
  // },
  // {
  //   name: 'how many people are there in your family',
  //   value: require('/assets/images/how many people are there in your family.gif'),
  // },
  // {name: 'i am a clerk', value: require('/assets/images/i am a clerk.gif')},
  // {
  //   name: 'i am bore doing nothing',
  //   value: require('/assets/images/i am bore doing nothing.gif'),
  // },
  // {name: 'i am fine', value: require('/assets/images/i am fine.gif')},
  // {name: 'i am sorry', value: require('/assets/images/i am sorry.gif')},
  // {name: 'i am thinking', value: require('/assets/images/i am thinking.gif')},
  // {name: 'i am tired', value: require('/assets/images/i am tired.gif')},
  // {
  //   name: 'i dont understand anything',
  //   value: require('/assets/images/i dont understand anything.gif'),
  // },
  // {
  //   name: 'i go to a theatre',
  //   value: require('/assets/images/i go to a theatre.gif'),
  // },
  // {name: 'i love to shop', value: require('/assets/images/i love to shop.gif')},
  // {
  //   name: 'i had to say something but I forgot',
  //   value: require('/assets/images/i had to say something but I forgot.gif'),
  // },
  // {
  //   name: 'i have headache',
  //   value: require('/assets/images/i have headache.gif'),
  // },
  // {
  //   name: 'i like pink colour',
  //   value: require('/assets/images/i like pink colour.gif'),
  // },
  // {
  //   name: 'i live in nagpur',
  //   value: require('/assets/images/i live in nagpur.gif'),
  // },
  // {
  //   name: 'lets go for lunch',
  //   value: require('/assets/images/lets go for lunch.gif'),
  // },
  // {
  //   name: 'my mother is a homemaker',
  //   value: require('/assets/images/my mother is a homemaker.gif'),
  // },
  // {
  //   name: 'my name is john',
  //   value: require('/assets/images/my name is john.gif'),
  // },
  // {
  //   name: 'nice to meet you',
  //   value: require('/assets/images/nice to meet you.gif'),
  // },
  // {
  //   name: 'no smoking please',
  //   value: require('/assets/images/no smoking please.gif'),
  // },
  // {name: 'open the door', value: require('/assets/images/open the door.gif')},
  // {
  //   name: 'please call me later',
  //   value: require('/assets/images/please call me later.gif'),
  // },
  // {
  //   name: 'please clean the room',
  //   value: require('/assets/images/please clean the room.gif'),
  // },
  // {
  //   name: 'please give me your pen',
  //   value: require('/assets/images/please give me your pen.gif'),
  // },
  // {
  //   name: 'please use dustbin dont throw garbage',
  //   value: require('/assets/images/please use dustbin dont throw garbage.gif'),
  // },
  "are you angry",
  "are you busy",
  "are you hungry",
  "are you sick",
  "be careful",
  "can we meet tomorrow",
  "did you book tickets",
  "did you finish homework",
  "do you go to office",
  "do you have money",
  "do you want something to drink",
  "do you want tea or coffee",
  "do you watch TV",
  "dont worry",
  "flower is beautiful",
  "good afternoon",
  "good evening",
  "good morning",
  "good night",
  "good question",
  "had your lunch",
  "happy journey",
  "hello what is your name",
  "how many people are there in your family",
  "i am a clerk",
  "i am bore doing nothing",
  "i am fine",
  "i am sorry",
  "i am thinking",
  "i am tired",
  "i dont understand anything",
  "i go to a theatre",
  "i love to shop",
  "i had to say something but I forgot",
  "i have headache",
  "i like pink colour",
  "i live in nagpur",
  "lets go for lunch",
  "my mother is a homemaker",
  "my name is john",
  "nice to meet you",
  "no smoking please",
  "open the door",
  "please call me later",
  "please clean the room",
  "please give me your pen",
  "please use dustbin dont throw garbage",
  "please wait for sometime",
  "shall I help you",
  "shall we go together tommorow",
  "sign language interpreter",
  "sit down",
  "stand up",
  "take care",
  "there was traffic jam",
  "wait I am thinking",
  "what are you doing",
  "what is the problem",
  "what is todays date",
  "what is your father do",
  "what is your job",
  "what is your mobile number",
  "what is your name",
  "whats up",
  "when is your interview",
  "when we will go",
  "where do you stay",
  "where is the bathroom",
  "where is the police station",
  "you are wrong",
  "address",
  "agra",
  "ahmedabad",
  "all",
  "april",
  "assam",
  "august",
  "australia",
  "badoda",
  "banana",
  "banaras",
  "banglore",
  "bihar",
  "bihar",
  "bridge",
  "cat",
  "chandigarh",
  "chennai",
  "christmas",
  "church",
  "clinic",
  "coconut",
  "crocodile",
  "dasara",
  "deaf",
  "december",
  "deer",
  "delhi",
  "dollar",
  "duck",
  "february",
  "friday",
  "fruits",
  "glass",
  "grapes",
  "gujarat",
  "hello",
  "hindu",
  "hyderabad",
  "india",
  "january",
  "jesus",
  "job",
  "july",
  "july",
  "karnataka",
  "kerala",
  "krishna",
  "litre",
  "mango",
  "may",
  "mile",
  "monday",
  "mumbai",
  "museum",
  "muslim",
  "nagpur",
  "october",
  "orange",
  "pakistan",
  "pass",
  "police station",
  "post office",
  "pune",
  "punjab",
  "rajasthan",
  "ram",
  "restaurant",
  "saturday",
  "september",
  "shop",
  "sleep",
  "southafrica",
  "story",
  "sunday",
  "tamil nadu",
  "temperature",
  "temple",
  "thursday",
  "toilet",
  "tomato",
  "town",
  "tuesday",
  "usa",
  "village",
  "voice",
  "wednesday",
  "weight",
  "please wait for sometime",
  "what is your mobile number",
  "what are you doing",
  "are you busy",
].map((item) => {
  return {
    name: item,
    value: require(`/assets/images/${item}.gif`),
  };
});

export const arr = [
  // {
  //   name: "a",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/A.jpg"),
  // },
  // {
  //   name: "b",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/B.jpg"),
  // },
  // {
  //   name: "c",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/C.jpg"),
  // },
  // {
  //   name: "d",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/D.jpg"),
  // },
  // {
  //   name: "e",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/E.jpg"),
  // },
  // {
  //   name: "f",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/F.jpg"),
  // },
  // {
  //   name: "g",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/G.jpg"),
  // },
  // {
  //   name: "h",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/H.jpg"),
  // },
  // {
  //   name: "i",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/I.jpg"),
  // },
  // {
  //   name: "j",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/J.jpg"),
  // },
  // {
  //   name: "k",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/K.jpg"),
  // },
  // {
  //   name: "l",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/L.jpg"),
  // },
  // {
  //   name: "m",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/M.jpg"),
  // },
  // {
  //   name: "n",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/N.jpg"),
  // },
  // {
  //   name: "o",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/O.jpg"),
  // },
  // {
  //   name: "p",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/P.jpg"),
  // },
  // {
  //   name: "q",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/Q.jpg"),
  // },
  // {
  //   name: "r",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/R.jpg"),
  // },
  // {
  //   name: "s",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/S.jpg"),
  // },
  // {
  //   name: "t",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/T.jpg"),
  // },
  // {
  //   name: "u",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/U.jpg"),
  // },
  // {
  //   name: "v",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/V.jpg"),
  // },
  // {
  //   name: "w",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/W.jpg"),
  // },
  // {
  //   name: "x",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/X.jpg"),
  // },

  // {
  //   name: "y",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/Y.jpg"),
  // },
  // {
  //   name: "z",
  //   value: require("/home/yus-vengeance/Desktop/project-7sem/disabilityBridge/assets/images/Z.jpg"),
  // },
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
].map((letter) => {
  return {
    name: letter,
    value: require(`/assets/images/${letter}.jpg`),
  };
});
